##ejemplo de invocacion
##https://github.com/jaysson1710-org/demo-core/blob/main/README_disptach.md
name: dispatch receiver

on: 
  repository_dispatch:
    types: [command]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'command' }}
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      run: |
        echo "repository_dispatch triggered"
        echo "parametros"
        echo ${{ github.event.client_payload.action }}
        echo "$#####################"
        echo "${{ toJson(github.event) }}"
