name: concurrent workflow

on: [workflow_dispatch]
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
          shell: bash
          working-directory: .
    runs-on: ubuntu-latest  
    steps:
      - name: test
        run: echo "$(PWD)"
