# This is a basic workflow to help you get started with Actions

name: github-commands

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::debug::Set debug info"
      - name: Create annotation for build error
        run: echo "::warning file=github_commands.yml,line=3::Error name"
      

