name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: jaysson1710-org/.github/.github/workflows/Workflow-Generic-template.yml@main
    with:
      config-path: .github/workflows/labeler.config.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
